<?xml version="1.0" encoding="utf-8"?>
<Database Name="SutekiShop" Class="ShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SutekiShop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SutekiShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserId" OtherKey="UserId" Type="Order" />
      <Association Name="User_Basket" Member="Baskets" ThisKey="UserId" OtherKey="UserId" Type="Basket" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Image" Member="Images">
    <Type Name="Image">
      <Column Name="ImageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Image_ProductImage" Member="ProductImages" ThisKey="ImageId" OtherKey="ImageId" Type="ProductImage" />
    </Type>
  </Table>
  <Table Name="dbo.BasketItem" Member="BasketItems">
    <Type Name="BasketItem">
      <Column Name="BasketItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BasketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SizeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Size_BasketItem" Member="Size" ThisKey="SizeId" OtherKey="SizeId" Type="Size" IsForeignKey="true" />
      <Association Name="Basket_BasketItem" Member="Basket" ThisKey="BasketId" OtherKey="BasketId" Type="Basket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CardType" Member="CardTypes">
    <Type Name="CardType">
      <Column Name="CardTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RequiredIssueNumber" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CardType_Card" Member="Cards" ThisKey="CardTypeId" OtherKey="CardTypeId" Type="Card" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ContactId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Contact_Order" Member="Orders" ThisKey="ContactId" OtherKey="CardContactId" Type="Order" />
      <Association Name="Contact_Order1" Member="Orders1" ThisKey="ContactId" OtherKey="DeliveryContactId" Type="Order" />
      <Association Name="Country_Contact" Member="Country" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Card" Member="Cards">
    <Type Name="Card">
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Holder" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IssueNumber" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SecurityCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Card_Order" Member="Orders" ThisKey="CardId" OtherKey="CardId" Type="Order" />
      <Association Name="CardType_Card" Member="CardType" ThisKey="CardTypeId" OtherKey="CardTypeId" Type="CardType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Postage" Member="Postages">
    <Type Name="Postage">
      <Column Name="PostageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxWeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleId" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostZoneId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Country_Contact" Member="Contacts" ThisKey="CountryId" OtherKey="CountryId" Type="Contact" />
      <Association Name="Country_Basket" Member="Baskets" ThisKey="CountryId" OtherKey="CountryId" Type="Basket" />
      <Association Name="PostZone_Country" Member="PostZone" ThisKey="PostZoneId" OtherKey="PostZoneId" Type="PostZone" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="OrderStatusId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="OrderStatus_Order" Member="Orders" ThisKey="OrderStatusId" OtherKey="OrderStatusId" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BasketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardContactId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryContactId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInformation" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UseCardHolderContact" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PayByTelephone" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DispatchedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Storage="_Comment" Type="System.String" CanBeNull="true" />
      <Column Name="ContactMe" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Card_Order" Member="Card" ThisKey="CardId" OtherKey="CardId" Type="Card" IsForeignKey="true" />
      <Association Name="Contact_Order" Member="Contact" ThisKey="CardContactId" OtherKey="ContactId" Type="Contact" IsForeignKey="true" />
      <Association Name="Contact_Order1" Member="Contact1" ThisKey="DeliveryContactId" OtherKey="ContactId" Type="Contact" IsForeignKey="true" />
      <Association Name="OrderStatus_Order" Member="OrderStatus" ThisKey="OrderStatusId" OtherKey="OrderStatusId" Type="OrderStatus" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Basket_Order" Member="Basket" ThisKey="BasketId" OtherKey="BasketId" Type="Basket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductImage" Member="ProductImages">
    <Type Name="ProductImage">
      <Column Name="ProductImageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Image_ProductImage" Member="Image" ThisKey="ImageId" OtherKey="ImageId" Type="Image" IsForeignKey="true" />
      <Association Name="Product_ProductImage" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostZone" Member="PostZones">
    <Type Name="PostZone">
      <Column Name="PostZoneId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Multiplier" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="AskIfMaxWeight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FlatRate" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="PostZone_Country" Member="Countries" ThisKey="PostZoneId" OtherKey="PostZoneId" Type="Country" />
    </Type>
  </Table>
  <Table Name="dbo.Size" Member="Sizes">
    <Type Name="Size">
      <Column Name="SizeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsInStock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Size_BasketItem" Member="BasketItems" ThisKey="SizeId" OtherKey="SizeId" Type="BasketItem" />
      <Association Name="Product_Size" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" CanBeNull="true" />
      <Association Name="Category_Category" Member="Categories" ThisKey="CategoryId" OtherKey="ParentId" Type="Category" />
      <Association Name="Category_ProductCategory" Member="ProductCategories" ThisKey="CategoryId" OtherKey="CategoryId" Type="ProductCategory" />
      <Association Name="Category_Category" Member="Category1" ThisKey="ParentId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="Image_Category" Member="Image" ThisKey="ImageId" OtherKey="ImageId" Type="Image" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentType" Member="ContentTypes">
    <Type Name="ContentType">
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ContentType_Content" Member="Contents" ThisKey="ContentTypeId" OtherKey="ContentTypeId" Type="Content" />
    </Type>
  </Table>
  <Table Name="dbo.Content" Member="Contents">
    <Type Name="Content" InheritanceCode="0">
      <Column Name="ContentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentContentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UrlName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Content_Content" Member="Contents" ThisKey="ContentId" OtherKey="ParentContentId" Type="Content" />
      <Association Name="Content_Content" Member="Content1" ThisKey="ParentContentId" OtherKey="ContentId" Type="Content" IsForeignKey="true" />
      <Association Name="ContentType_Content" Member="ContentType" ThisKey="ContentTypeId" OtherKey="ContentTypeId" Type="ContentType" IsForeignKey="true" />
      <Type Name="Menu" InheritanceCode="1" IsInheritanceDefault="true" />
      <Type Name="TextContent" InheritanceCode="2">
        <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      </Type>
      <Type Name="ActionContent" InheritanceCode="3">
        <Column Name="Controller" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
        <Column Name="Action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      </Type>
      <Type Name="TopContent" InheritanceCode="4">
        <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      </Type>
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UrlName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductImage" Member="ProductImages" ThisKey="ProductId" OtherKey="ProductId" Type="ProductImage" />
      <Association Name="Product_Size" Member="Sizes" ThisKey="ProductId" OtherKey="ProductId" Type="Size" />
      <Association Name="Product_ProductCategory" Member="ProductCategories" ThisKey="ProductId" OtherKey="ProductId" Type="ProductCategory" />
      <Association Name="Product_Review" Member="Reviews" ThisKey="ProductId" OtherKey="ProductId" Type="Review" />
    </Type>
  </Table>
  <Table Name="dbo.Basket" Member="Baskets">
    <Type Name="Basket">
      <Column Name="BasketId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Basket_BasketItem" Member="BasketItems" ThisKey="BasketId" OtherKey="BasketId" Type="BasketItem" />
      <Association Name="Basket_Order" Member="Orders" ThisKey="BasketId" OtherKey="BasketId" Type="Order" />
      <Association Name="Country_Basket" Member="Country" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" />
      <Association Name="User_Basket" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductCategory" Member="ProductCategories">
    <Type Name="ProductCategory">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="int NOT NULL Identity" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" CanBeNull="false" />
      <Association Name="Category_ProductCategory" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="Product_ProductCategory" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="Reviews">
    <Type Name="Review">
      <Column Name="Id" Type="int" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Approved" Type="System.Boolean" CanBeNull="false" />
      <Column Name="Text" Type="System.String" CanBeNull="false" />
      <Column Name="Rating" Type="int" CanBeNull="false" />
      <Column Name="Reviewer" Type="System.String" DbType="nvarchar(250)" CanBeNull="false" />
      <Association Name="Product_Review" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="MailingListSubscriptions">
    <Type Name="MailingListSubscription">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="nvarchar(250)" CanBeNull="true" />
      <Column Name="ContactId" Type="System.Int32" CanBeNull="false" />
      <Column Name="DateSubscribed" AutoSync="OnInsert" Type="System.DateTime" DbType="DATETIME" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Contact_MailingListSubscription" Member="Contact" ThisKey="ContactId" OtherKey="ContactId" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
</Database>